### ISSUE TITLE
Endpoint: busca pelo paciente (nome e CPF)

### ISSUE THREAD

**Issue by professorarenatabraga** [OCDP/ocdp-front-end-mobile#19]

**Comment by leandropedrosa** [comment]
O endpoint: http://api-ocdp.us-east-2.elasticbeanstalk.com:8080/api/historico/pacientes/João

[
  {
    "id": "1",
    "nome": "João",
    "cpf": "999.999.999-99",
    "dataNascimento": "2020-04-10T16:30:16.613+0000",
    "sexo": "MASCULINO",
    "email": "teste@teste.com",
    "telefoneCelular": "62 9999-9999",
    "nomeDaMae": "Maria",
    "telefoneResponsavel": "62 9999-9999",
    "bairro": {
      "id": "1",
      "nome": "ANDREIA CRISTINA"
    },
    "enderecoCompleto": "Teste teste testetes"
  },
  {
    "id": "2",
    "nome": "João",
    "cpf": "999.999.999-99",
    "dataNascimento": "2020-04-10T16:30:17.028+0000",
    "sexo": "MASCULINO",
    "email": "teste@teste.com",
    "telefoneCelular": "62 9999-9999",
    "nomeDaMae": "Maria",
    "telefoneResponsavel": "62 9999-9999",
    "bairro": {
      "id": "1",
      "nome": "ANDREIA CRISTINA"
    },
    "enderecoCompleto": "Teste teste testetes"
  },
  {
    "id": "3",
    "nome": "João",
    "cpf": "999.999.999-99",
    "dataNascimento": "2020-04-10T16:30:17.429+0000",
    "sexo": "MASCULINO",
    "email": "teste@teste.com",
    "telefoneCelular": "62 9999-9999",
    "nomeDaMae": "Maria",
    "telefoneResponsavel": "62 9999-9999",
    "bairro": {
      "id": "1",
      "nome": "ANDREIA CRISTINA"
    },
    "enderecoCompleto": "Teste teste testetes"
  }
]

Fica a cargo do front colocar nome+"  "+cpf na vizualização
