### ISSUE TITLE
Exibir Histórico Paciente | Mobile

### ISSUE THREAD

**Issue by wevertoum** [OCDP/ocdp-front-end-mobile#6]
Após localizar o paciente, exibe seu histórico de saúde (ordem decrescente) 
[fluxo de dados](https://docs.google.com/document/d/1garFA8yhGY9ULp7cT9r8w7NWHA-YzpcdJkrVVXQ4m5U/edit)  
[modelo de dados](https://github.com/OCDP/artefatos/tree/master/Artefatos%20projeto/DER)

**Comment by professorarenatabraga** [comment]
O histórico já está concluído, certo? Já consta na lista todos os atendimentos recebidos. Falta apenas visualizar um determinado atendimento. Se for isto, pode concluir essa Issue @wevertoum
